[project]
name = "monte-carlo-widget"
version = "0.1.0"
description = "Monte Carlo simulation widget for OpenBB"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "plotly>=5.17.0",
    "pandas>=2.1.0",
    "numpy>=1.25.0",
    "yfinance>=0.2.0",
]